web:
  hostname: 0.0.0.0
  port: 8000

redis:
  hostname: c2-redis-service
  port: 6379
  channel_session: c2_session
  channel_payload: c2_payload

database:
  hostname: c2-db-service
  port: 5432
  username: c2redteam
  password: sEPkp7eK7q3xgV
  database: postgres

tcp_server:
  ip: 0.0.0.0
  port: 8888
  max_retry_count: 5
  socket_buffer_size: 4096

logger:
  level: INFO